/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Participant } from "../types/Participant";

export const Request: core.serialization.Schema<
    serializers.handlePostSessionParticipantInboxSessionsSessionIdParticipantsPost.Request.Raw,
    Scout.Participant[]
> = core.serialization.list(Participant);

export declare namespace Request {
    export type Raw = Participant.Raw[];
}
