/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../../../index";

/**
 * @example
 *     {
 *         input: {
 *             "key": 1
 *         }
 *     }
 */
export interface WorkflowsExecuteRequest extends Scout.ReqBody {
    revisionId?: string;
    sessionId?: string;
}
