/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../../../index.js";

/**
 * @example
 *     {
 *         workflow_id: "workflow_id",
 *         workflow_key: "workflow_key",
 *         body: {}
 *     }
 */
export interface WorkflowsCreateRevisionRequest {
    workflow_id?: string;
    workflow_key?: string;
    body: Scout.WorkflowConfigInput;
}
