/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scout from "../../../../api/index";
import * as core from "../../../../core";

export const DocumentsUpdateRequestValue: core.serialization.Schema<
    serializers.DocumentsUpdateRequestValue.Raw,
    Scout.DocumentsUpdateRequestValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.boolean(),
    core.serialization.number(),
    core.serialization.number(),
    core.serialization.string(),
]);

export declare namespace DocumentsUpdateRequestValue {
    export type Raw = boolean | number | number | string;
}
