/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scout from "../../../../api/index";
import * as core from "../../../../core";
import { DocumentsUpdateBatchRequestBodyZeroValue } from "./DocumentsUpdateBatchRequestBodyZeroValue";
import { DocumentsUpdateBatchRequestBodyOneValue } from "./DocumentsUpdateBatchRequestBodyOneValue";
import { DocumentsUpdateBatchRequestBodyItemValue } from "./DocumentsUpdateBatchRequestBodyItemValue";

export const DocumentsUpdateBatchRequestBody: core.serialization.Schema<
    serializers.DocumentsUpdateBatchRequestBody.Raw,
    Scout.DocumentsUpdateBatchRequestBody
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), DocumentsUpdateBatchRequestBodyZeroValue),
    core.serialization.record(core.serialization.string(), DocumentsUpdateBatchRequestBodyOneValue.optional()),
    core.serialization.list(
        core.serialization.record(core.serialization.string(), DocumentsUpdateBatchRequestBodyItemValue),
    ),
    core.serialization.list(
        core.serialization.record(core.serialization.string(), DocumentsUpdateBatchRequestBodyItemValue.optional()),
    ),
]);

export declare namespace DocumentsUpdateBatchRequestBody {
    export type Raw =
        | Record<string, DocumentsUpdateBatchRequestBodyZeroValue.Raw>
        | Record<string, DocumentsUpdateBatchRequestBodyOneValue.Raw | null | undefined>
        | Record<string, DocumentsUpdateBatchRequestBodyItemValue.Raw>[]
        | Record<string, DocumentsUpdateBatchRequestBodyItemValue.Raw | null | undefined>[];
}
