/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface UsageGetRequest {
    /**
     * Start date for the usage data
     */
    start_date?: string;
    /**
     * End date for the usage data
     */
    end_date?: string;
}
