/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Scout from "../../../api/index";
import * as core from "../../../core";
import { PlanTypes } from "../../types/PlanTypes";

export const Plan: core.serialization.Schema<serializers.Plan.Raw, Scout.Plan> = core.serialization.object({
    name: PlanTypes,
});

export declare namespace Plan {
    export interface Raw {
        name: PlanTypes.Raw;
    }
}
