/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Scout from "../../../api/index";
import * as core from "../../../core";
import { SrcAppHttpRoutesDriveCreateDriveCrawlPayloadSourceSyncSettings } from "../../types/SrcAppHttpRoutesDriveCreateDriveCrawlPayloadSourceSyncSettings";
import { Schedule } from "../../types/Schedule";

export const SrcAppHttpRoutesDriveCreateDriveCrawlPayload: core.serialization.Schema<
    serializers.SrcAppHttpRoutesDriveCreateDriveCrawlPayload.Raw,
    Scout.SrcAppHttpRoutesDriveCreateDriveCrawlPayload
> = core.serialization.object({
    source_sync_settings: SrcAppHttpRoutesDriveCreateDriveCrawlPayloadSourceSyncSettings,
    schedule: Schedule.optional(),
    url: core.serialization.string(),
});

export declare namespace SrcAppHttpRoutesDriveCreateDriveCrawlPayload {
    export interface Raw {
        source_sync_settings: SrcAppHttpRoutesDriveCreateDriveCrawlPayloadSourceSyncSettings.Raw;
        schedule?: Schedule.Raw | null;
        url: string;
    }
}
