/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Scout from "../../../api/index";
import * as core from "../../../core";

export const UpdateEntityRequest: core.serialization.Schema<
    serializers.UpdateEntityRequest.Raw,
    Scout.UpdateEntityRequest
> = core.serialization.object({
    id: core.serialization.string(),
    updates: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace UpdateEntityRequest {
    export interface Raw {
        id: string;
        updates: Record<string, unknown>;
    }
}
