/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         workflow_id: "string",
 *         start_date: "string",
 *         end_date: "string",
 *         limit: 1,
 *         session_id: "string",
 *         status: "string",
 *         cursor: "string"
 *     }
 */
export interface WorkflowLogsListLogsRequest {
    workflow_id: string;
    start_date?: string;
    end_date?: string;
    limit?: number;
    session_id?: string;
    status?: string;
    cursor?: string;
}
