/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../../index";

export type DocumentsCreateRequest =
    | Record<string, Scout.DocumentsCreateRequestZeroValue>
    | Record<string, Scout.DocumentsCreateRequestItemValue>[];
