/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../../index.js";

export type WorkflowLogsListLogsResponse = Scout.RunLog | Scout.RunLogPagination;
