// This file was auto-generated by Fern from our API Definition.

export const ActionType = {
    WorkflowExecute: "workflow.execute",
    SourceSync: "source.sync",
} as const;
export type ActionType = (typeof ActionType)[keyof typeof ActionType];
