// This file was auto-generated by Fern from our API Definition.

export interface ActorIdentity {
    type: ActorIdentity.Type;
    id: ActorIdentity.Id;
}

export namespace ActorIdentity {
    export const Type = {
        Organization: "organization",
        User: "user",
        Agent: "agent",
        System: "system",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export type Id = string | "system";
}
