// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface Actor {
    scout_organization_id: string;
    identity: Scout.LegacyIdentity;
    actor_identity: Scout.ActorIdentity;
}
