// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface AgentRevisionUpdate {
    model_provider?: Scout.ModelProvider;
    model: AgentRevisionUpdate.Model;
    system: string;
    temperature?: number;
    response_style?: AgentRevisionUpdate.ResponseStyle;
    max_tokens?: number;
    max_turns?: number;
    tool_config?: Record<string, AgentRevisionUpdate.ToolConfig.Value | undefined>;
    conversation_starters?: string[];
    dynamic_fallbacks?: Scout.AgenticModel[];
}

export namespace AgentRevisionUpdate {
    export type Model = "_dynamic" | string;
    export const ResponseStyle = {
        Precise: "precise",
        Balanced: "balanced",
        Creative: "creative",
        Experimental: "experimental",
        Json: "json",
    } as const;
    export type ResponseStyle = (typeof ResponseStyle)[keyof typeof ResponseStyle];

    export namespace ToolConfig {
        export type Value = boolean | Scout.ToolConfigResource[];
    }
}
