// This file was auto-generated by Fern from our API Definition.

/**
 * Optional agent configuration overrides.
 *
 * Product faces send only the fields they want to override.
 * Omitted fields (None) use platform defaults.
 *
 * The model field accepts a single model name or an ordered list.
 * If a list, the first entry is the primary model and the rest are
 * fallbacks tried in order if the primary fails. Model provider
 * (Anthropic, OpenAI, Google) is derived automatically from the
 * model name.
 *
 * Platform defaults:
 * - model: "claude-haiku-4-5"
 * - temperature: 0.3
 * - max_tokens: 32000
 */
export interface AgentConfig {
    /** LLM model name or ordered list of model names. First is primary, rest are fallbacks. Provider derived from name (e.g., "gpt-4o" → OpenAI, "claude-sonnet-4-5" → Anthropic, "gemini-2.5-flash" → Google). Default: "claude-haiku-4-5". */
    model?: AgentConfig.Model;
    /** LLM temperature. Default: 0.3. */
    temperature?: number;
    /** Maximum output tokens per LLM call. Default: 32000. */
    max_tokens?: number;
    /** Tool names to enable for the agent. Platform always enables emit_atoms. Product can request integration tools (e.g., 'Salesforce__salesforce_query'). Default: [] (no additional tools). */
    tools?: string[];
}

export namespace AgentConfig {
    /**
     * LLM model name or ordered list of model names. First is primary, rest are fallbacks. Provider derived from name (e.g., "gpt-4o" → OpenAI, "claude-sonnet-4-5" → Anthropic, "gemini-2.5-flash" → Google). Default: "claude-haiku-4-5".
     */
    export type Model = string | string[];
}
