/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface AppConfigInput {
    appDisplayName?: string;
    appSchemaVersion?: string;
    appImgUrl?: string;
    appDescription?: string;
    blocks?: Scout.BlockInput[];
}
