// This file was auto-generated by Fern from our API Definition.

/**
 * Result of a single assertion check
 */
export interface AssertionResult {
    assertion?: unknown;
    /** Type of assertion (redundant with assertion.type) */
    assertion_type: AssertionResult.AssertionType;
    /** JSON path to field being checked (e.g., 'response.products[0].id') */
    field_path?: string;
    /** Expected value */
    expected_value?: unknown;
    /** Actual value from output */
    actual_value?: unknown;
    /** Whether assertion passed */
    passed: boolean;
    /** Numeric score for similarity checks (0-1) */
    score?: number;
    /** Human-readable assertion description */
    description: string;
    /** Error message if assertion failed */
    error_message?: string;
}

export namespace AssertionResult {
    /** Type of assertion (redundant with assertion.type) */
    export const AssertionType = {
        ExactMatch: "exact_match",
        Contains: "contains",
        RegexMatch: "regex_match",
        SemanticSimilarity: "semantic_similarity",
        FieldExists: "field_exists",
        TypeCheck: "type_check",
        LlmJudge: "llm_judge",
    } as const;
    export type AssertionType = (typeof AssertionType)[keyof typeof AssertionType];
}
