// This file was auto-generated by Fern from our API Definition.

/**
 * Request model for batch inviting bot to channels
 */
export interface BatchInviteRequest {
    channel_ids: string[];
    team_id?: string;
}
