/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The limits associated with the organizations billing plan.
 *
 * Default to free tier limits, while allowing the ability to override.
 * In the checking of limits, for now we will only enforce the limits
 * if the billing plan is of the "free" tier aka "plan_1".
 *
 * Eventually we might want to enforce limits on paid plans, where
 * when we change the plan, we can update the limits in business logic.
 */
export interface BillingLimits {
    seats?: number;
    agent_interactions?: number;
    integrations?: number;
    workflow_invocations?: number;
    active_workflows?: number;
}
