// This file was auto-generated by Fern from our API Definition.

import * as Scout from "../index.js";

export interface Billing {
    provider?: Scout.StripeProvider;
    subscriptions?: Scout.Subscription[];
    renewal_date?: string;
    limits?: Scout.BillingLimits;
    usage?: Scout.BillingUsage;
}
