/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface BlockRunFailed {
    organization_id: string;
    /** The unique identifier of the event */
    id?: string;
    /** Identifies the root cause of the event. If not set, it defaults to the event id. */
    correlation_id?: string;
    name: "block_run_failed";
    environment: BlockRunFailed.Environment;
    /** The timestamp of the event as UTC ISO 8601 string */
    timestamp?: string;
    data: Scout.BlockRunFailedData;
    price?: string;
    event_type?: string;
    version: Scout.EventVersion;
}

export namespace BlockRunFailed {
    export type Environment = "development" | "preview" | "production" | "test";
    export const Environment = {
        Development: "development",
        Preview: "preview",
        Production: "production",
        Test: "test",
    } as const;
}
