/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BlockStateUpdatedEnvironment = "development" | "preview" | "production" | "test";
export const BlockStateUpdatedEnvironment = {
    Development: "development",
    Preview: "preview",
    Production: "production",
    Test: "test",
} as const;
