/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BlockConfigItemBoolean {
    id: string;
    display_name: string;
    type: "boolean";
    default_value?: boolean;
    value?: boolean;
}
