/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BlockConfigItemTextShort {
    id: string;
    display_name: string;
    type: "text-short";
    default_value?: string;
    value?: string;
}
