/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BlockRunStartedData {
    workflowId: string;
    workflowRunId: string;
    blockId?: string;
    config: Record<string, unknown>;
    metadata?: Record<string, unknown>;
    state: Record<string, unknown>;
    sessionId: string;
}
