// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * A briefing run (execution record).
 */
export interface BriefingRun {
    id: string;
    config_id: string;
    organization_id: string;
    status: BriefingRun.Status;
    started_at?: string;
    completed_at?: string;
    agent_session_id?: string;
    result?: Scout.BriefingOutput;
    delivery_status?: Record<string, string>;
    error?: string;
    created_at: string;
}

export namespace BriefingRun {
    export const Status = {
        Pending: "pending",
        Running: "running",
        Completed: "completed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
