// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * Input for updating a copilot config.
 */
export interface BriefingCopilotConfigUpdate {
    name?: string;
    layout_id?: string;
    schedule?: Scout.CopilotSchedule;
    recipients?: string[];
    is_active?: boolean;
}
