// This file was auto-generated by Fern from our API Definition.

/**
 * Schedule configuration for a briefing.
 */
export interface BriefingSchedule {
    day: BriefingSchedule.Day;
    time: string;
    timezone?: string;
}

export namespace BriefingSchedule {
    export const Day = {
        Monday: "Monday",
        Tuesday: "Tuesday",
        Wednesday: "Wednesday",
        Thursday: "Thursday",
        Friday: "Friday",
        Saturday: "Saturday",
        Sunday: "Sunday",
    } as const;
    export type Day = (typeof Day)[keyof typeof Day];
}
