// This file was auto-generated by Fern from our API Definition.

/**
 * Bring Your Own outputs target.
 *
 * For evaluating pre-computed outputs without execution.
 * Used by POST /evaluation/evaluate endpoint.
 *
 * Example:
 *     target = BYOTarget(
 *         type="byo",
 *         source="local_function"
 *     )
 */
export interface ByoTarget {
    type: "byo";
    /** Specific revision/version to evaluate */
    revision_id?: string;
    /** Target-specific metadata */
    metadata?: Record<string, unknown>;
    /** Optional description of output source (e.g., 'local_function', 'external_api') */
    source?: string;
}
