// This file was auto-generated by Fern from our API Definition.

/**
 * A change/event item.
 */
export interface ChangeBlock {
    type: "change";
    change_type: ChangeBlock.ChangeType;
    description: string;
    deal_name?: string;
    amount?: string;
    icon?: string;
}

export namespace ChangeBlock {
    export const ChangeType = {
        Won: "won",
        Lost: "lost",
        Slipped: "slipped",
        New: "new",
        StageChange: "stage_change",
        AmountChange: "amount_change",
    } as const;
    export type ChangeType = (typeof ChangeType)[keyof typeof ChangeType];
}
