/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface CollectionConfigOutput {
    collectionDisplayName?: string;
    collectionImgUrl?: string;
    collectionDescription?: string;
    columns?: Scout.CollectionConfigOutputColumnsItem[];
}
