// This file was auto-generated by Fern from our API Definition.

export interface CollectionConfig {
    collection_display_name?: string;
    collection_img_url?: string;
    collection_description?: string;
    tags?: string[];
    table_order?: string[];
}
