/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ColumnTypeItemCheckBox {
    columnId?: string;
    columnDisplayName?: string;
    columnType: "boolean";
    defaultValue?: boolean;
    dataType?: "boolean";
}
