// This file was auto-generated by Fern from our API Definition.

export const ColumnType = {
    Checkbox: "checkbox",
    Json: "json",
    Number: "number",
    Select: "select",
    MultiSelect: "multi-select",
    TextLong: "text-long",
    TextShort: "text-short",
    Datetime: "datetime",
    Url: "url",
    Markdown: "markdown",
    Relation: "relation",
    People: "people",
} as const;
export type ColumnType = (typeof ColumnType)[keyof typeof ColumnType];
