/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ColumnTypeItemUrl {
    column_id?: string;
    column_display_name?: string;
    column_type: "url";
    url?: string;
    data_type?: "string";
}
