/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface ColumnTypeBase {
    column_id?: string;
    column_display_name?: string;
    column_type: Scout.ColumnType;
    data_type: Scout.DataType;
    hidden?: boolean;
    /** Optional automation configuration to automatically calculate values for this column */
    automation_config: Scout.TypescriptAutomationConfig;
}
