/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ColumnTypeItemJson {
    columnId?: string;
    columnDisplayName?: string;
    columnType: "json";
    defaultValue?: string;
    dataType?: "json";
}
