/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ColumnTypeItemUrl {
    columnId?: string;
    columnDisplayName?: string;
    columnType: "url";
    url?: string;
    dataType?: "string";
}
