/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConditionField =
    | "channel_id"
    | "team_id"
    | "user_id"
    | "thread_id"
    | "user_message"
    | "is_first_message_in_thread"
    | "channel_name"
    | "bot_is_mentioned"
    | "is_bot_message";
export const ConditionField = {
    ChannelId: "channel_id",
    TeamId: "team_id",
    UserId: "user_id",
    ThreadId: "thread_id",
    UserMessage: "user_message",
    IsFirstMessageInThread: "is_first_message_in_thread",
    ChannelName: "channel_name",
    BotIsMentioned: "bot_is_mentioned",
    IsBotMessage: "is_bot_message",
} as const;
