// This file was auto-generated by Fern from our API Definition.

export interface Condition {
    field: Condition.Field;
    operator: Condition.Operator;
    value: string[];
}

export namespace Condition {
    export const Field = {
        ChannelId: "channel_id",
        TeamId: "team_id",
        UserId: "user_id",
        ThreadId: "thread_id",
        UserMessage: "user_message",
        IsFirstMessageInThread: "is_first_message_in_thread",
        ChannelName: "channel_name",
        BotIsMentioned: "bot_is_mentioned",
        IsBotMessage: "is_bot_message",
    } as const;
    export type Field = (typeof Field)[keyof typeof Field];
    export const Operator = {
        AnyOf: "Any Of",
        NoneOf: "None Of",
        IsTrue: "Is true",
        IsFalse: "Is false",
        IsNull: "Is null",
        IsNotNull: "Is not null",
        ContainsAnyOf: "Contains Any Of",
        ContainsNoneOf: "Contains None Of",
    } as const;
    export type Operator = (typeof Operator)[keyof typeof Operator];
}
