/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface CopilotConfig {
    workflow_id?: string;
    img_url?: string;
    display_name?: string;
    mode?: Scout.CopilotConfigMode;
    colors?: Record<string, string>;
    fab?: Record<string, Scout.CopilotConfigFabValue | undefined>;
    message_placeholder?: string;
    initial_activity?: unknown[];
    allowed_origins?: string;
}
