/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CopilotConfigMode = "light" | "dark";

export const CopilotConfigMode = {
    Light: "light",
    Dark: "dark",
} as const;
