// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * Request to create a saved evaluation
 */
export interface CreateEvaluationRequest {
    /** Evaluation name */
    name: string;
    /** Evaluation description */
    description?: string;
    /** Evaluation configuration */
    config: Scout.EvaluationConfigInput;
}
