/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export type DateTimeColumnAutomationConfig =
    | Scout.AgentAutomationConfig
    | Scout.TypescriptAutomationConfig
    | Scout.WorkflowAutomationConfig;
