// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface DateTimeColumn {
    column_id?: string;
    column_display_name?: string;
    column_type: "datetime";
    data_type?: "datetime";
    hidden?: boolean;
    /** Optional automation configuration to automatically calculate values for this column */
    automation_config: Scout.TypescriptAutomationConfig;
    default?: string;
}
