// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * Deal/opportunity card.
 */
export interface DealCardBlock {
    type: "deal_card";
    id: string;
    name: string;
    account: string;
    amount: string;
    close_date: string;
    stage: string;
    owner?: string;
    risk_level?: DealCardBlock.RiskLevel;
    risk_reason?: string;
    recommendation?: string;
    actions?: Scout.BlockAction[];
}

export namespace DealCardBlock {
    export const RiskLevel = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type RiskLevel = (typeof RiskLevel)[keyof typeof RiskLevel];
}
