/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * API response for deleting a hook.
 */
export interface DeleteHookResponse {
    success: boolean;
    message: string;
}
