// This file was auto-generated by Fern from our API Definition.

export interface Details {
    vector_distance?: number;
    bm25_score?: number;
    hybrid_score?: number;
    similarity_score?: number;
}
