/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Document {
    document_id?: string;
    data: Scout.DocumentDataOutput;
    created_at?: string;
    last_updated_at?: string;
    created_by: Scout.Identity;
    last_updated_by: Scout.Identity;
}
