/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Document {
    documentId?: string;
    data: Scout.DocumentDataOutput;
    createdAt?: Date;
    lastUpdatedAt?: Date;
    createdBy: Scout.Identity;
    lastUpdatedBy: Scout.Identity;
}
