/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface EnvironmentDeploymentDocument {
    deployment_id: string;
    environment_id: string;
    deployment_config: Scout.EnvironmentDeploymentConfig;
    created_at: Date;
    created_by: Scout.Identity;
}
