// This file was auto-generated by Fern from our API Definition.

/**
 * Execute scorer response
 */
export interface ExecuteScorerResponse {
    ok?: boolean;
    passed: boolean;
    overall_score: number;
    detailed_scores?: Record<string, number>;
    reasoning: string;
    execution_time_ms: number;
    session_id?: string;
    model?: string;
    error?: string;
    message?: string;
}
