// This file was auto-generated by Fern from our API Definition.

export const FilterOperator = {
    Equals: "equals",
    NotEquals: "not_equals",
    Contains: "contains",
    NotContains: "not_contains",
    StartsWith: "starts_with",
    EndsWith: "ends_with",
    IsEmpty: "is_empty",
    IsNotEmpty: "is_not_empty",
    GreaterThan: "greater_than",
    LessThan: "less_than",
    GreaterThanOrEqual: "greater_than_or_equal",
    LessThanOrEqual: "less_than_or_equal",
    Between: "between",
    In: "in",
    NotIn: "not_in",
    DateIs: "date_is",
    DateBefore: "date_before",
    DateAfter: "date_after",
    DateBetween: "date_between",
    DateIsEmpty: "date_is_empty",
    DateIsNotEmpty: "date_is_not_empty",
    IsTrue: "is_true",
    IsFalse: "is_false",
} as const;
export type FilterOperator = (typeof FilterOperator)[keyof typeof FilterOperator];
