// This file was auto-generated by Fern from our API Definition.

/**
 * On top of feature flags fetched from our port, we can also have other flags that
 * are derived solely from business logic. This is where we would add those.
 */
export interface Flags {
    automation_columns?: boolean;
    team_workspace?: boolean;
    token_counts?: boolean;
    copilot_greeting?: boolean;
    copilot_powered_by?: boolean;
    copilot_shadow?: boolean;
    copilot_show_scrollbar?: boolean;
    copilot_fab_additional_options?: boolean;
    nav_evaluations?: boolean;
    nav_scorers?: boolean;
    nav_feedback?: boolean;
    feedback_discussion?: boolean;
    drive_integrations?: boolean;
    self_service?: boolean;
}
