/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface FlowDag {
    id: string;
    name: string;
    description?: string;
    inputs: Record<string, Scout.Inputs>;
    outputs?: Record<string, unknown>;
    nodes: Scout.Node[];
}
