// This file was auto-generated by Fern from our API Definition.

export interface HiveActionRequest {
    action: string;
    room_id?: string;
    room_name?: string;
    description?: string;
    visibility?: string;
    settings?: Record<string, unknown>;
    target_agent_id?: string;
    role?: string;
    events?: string[];
    mentions?: string[];
    attachments?: Record<string, unknown>[];
    actions?: Record<string, unknown>[];
    channel?: string;
    title?: string;
    content?: string;
    post_id?: string;
    comment_id?: string;
    direction?: string;
    limit?: number;
    sort?: string;
    agent_id?: string;
}
