// This file was auto-generated by Fern from our API Definition.

export const IdentityTypes = {
    User: "user",
    ApiKey: "api_key",
    System: "system",
} as const;
export type IdentityTypes = (typeof IdentityTypes)[keyof typeof IdentityTypes];
