/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Identity {
    type: Scout.IdentityTypes;
    details: Scout.IdentityDetails;
}
