/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Invoice {
    id: string;
    meta: Scout.InvoiceMeta;
    status: Scout.InvoiceStatus;
    description: string;
    line_items: Scout.LineItem[];
    created_at: Date;
    paid_at?: Date;
    updated_at: Date;
    provider_meta?: Scout.StripeProviderMeta;
}
