/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface JsonColumn {
    column_id?: string;
    column_display_name?: string;
    column_type: "json";
    data_type?: "string";
    hidden?: boolean;
    default?: string;
}
