// This file was auto-generated by Fern from our API Definition.

/**
 * A subset of the Organization type that only
 * contains public-friendly condensed organization, mainly
 * the information to display it
 */
export interface MeOrganization {
    doc_type?: "organization";
    id: string;
    name: string;
    slug: string;
    profile_asset_url?: string;
}
