// This file was auto-generated by Fern from our API Definition.

/**
 * Native code-based scorer implemented in Python.
 *
 * Native scorers are fast, type-safe, and have direct access
 * to the codebase. They use typed config models from configs.py.
 *
 * Example:
 *     scorer = NativeScorer(
 *         id="exact_match",
 *         name="Exact Match",
 *         type="native",
 *         config_type="exact_match",
 *         description="Deep equality check",
 *         pass_threshold=1.0
 *     )
 */
export interface NativeScorer {
    type: "native";
    /** Unique scorer identifier */
    id: string;
    /** Human-readable scorer name */
    name: string;
    /** What this scorer evaluates */
    description: string;
    /** Optional pass/fail threshold (0-1) */
    pass_threshold?: number;
    /** Categorization tags */
    tags?: string[];
    /** Which config schema this scorer uses */
    config_type: NativeScorer.ConfigType;
}

export namespace NativeScorer {
    /** Which config schema this scorer uses */
    export const ConfigType = {
        ExactMatch: "exact_match",
        Contains: "contains",
        RegexMatch: "regex_match",
        FieldExists: "field_exists",
        TypeCheck: "type_check",
    } as const;
    export type ConfigType = (typeof ConfigType)[keyof typeof ConfigType];
}
