// This file was auto-generated by Fern from our API Definition.

export const NotificationActionType = {
    Primary: "primary",
    Secondary: "secondary",
} as const;
export type NotificationActionType = (typeof NotificationActionType)[keyof typeof NotificationActionType];
