/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NotionFilterBy = "Page URL" | "Page Title";
export const NotionFilterBy = {
    PageUrl: "Page URL",
    PageTitle: "Page Title",
} as const;
