/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface PeopleColumn {
    column_id?: string;
    column_display_name?: string;
    column_type: "people";
    data_type?: "string[]";
    hidden?: boolean;
    /** Optional automation configuration to automatically calculate values for this column */
    automation_config?: Scout.TypescriptAutomationConfig;
    allow_multiple?: boolean;
    /** Available options for selection */
    options?: Scout.SelectOptionItem[];
}
