/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface PlaceholderOutput {
    block_id: string;
    type: Scout.PlaceholderOutputType;
    ui?: Scout.NodeUi;
    dependencies?: Scout.Dependency[];
}
