/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface PlaceholderOutput {
    block_id: string;
    type: PlaceholderOutput.Type;
    ui?: Scout.NodeUi;
    dependencies?: Scout.Dependency[];
}

export namespace PlaceholderOutput {
    export type Type = "triggerPlaceholder" | "blockPlaceholder";
    export const Type = {
        TriggerPlaceholder: "triggerPlaceholder",
        BlockPlaceholder: "blockPlaceholder",
    } as const;
}
