// This file was auto-generated by Fern from our API Definition.

export interface Prompt {
    id: string;
    role: Prompt.Role;
    content: string;
}

export namespace Prompt {
    export const Role = {
        Assistant: "assistant",
        User: "user",
        System: "system",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
