/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Prompt {
    id: string;
    role: Scout.PromptRole;
    content: string;
}
