// This file was auto-generated by Fern from our API Definition.

/**
 * Prompt template evaluation target (future).
 *
 * Evaluates prompt templates with different models.
 *
 * Example:
 *     target = PromptTarget(
 *         type="prompt",
 *         prompt_template_id="prompt_product_description",
 *         model="claude-sonnet-4"
 *     )
 */
export interface PromptTarget {
    type: "prompt";
    /** Specific revision/version to evaluate */
    revision_id?: string;
    /** Target-specific metadata */
    metadata?: Record<string, unknown>;
    /** Prompt template ID to evaluate */
    prompt_template_id: string;
    /** Model to execute prompt with */
    model?: string;
}
