// This file was auto-generated by Fern from our API Definition.

/**
 * Public copilot configuration without sensitive fields.
 */
export interface PublicCopilotConfig {
    workflow_id?: string;
    img_url?: string;
    display_name?: string;
    mode?: PublicCopilotConfig.Mode;
    code_theme?: PublicCopilotConfig.CodeTheme;
    colors?: Record<string, string>;
    fab?: Record<string, PublicCopilotConfig.Fab.Value | undefined>;
    loading_text?: string;
    message_placeholder?: string;
    initial_activity?: unknown[];
    powered_by?: string;
}

export namespace PublicCopilotConfig {
    export const Mode = {
        Light: "light",
        Dark: "dark",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    export const CodeTheme = {
        Light: "light",
        Dark: "dark",
        None: "none",
    } as const;
    export type CodeTheme = (typeof CodeTheme)[keyof typeof CodeTheme];

    export namespace Fab {
        export type Value = number | string;
    }
}
