/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface QuerySort {
    column_id: string;
    direction: Scout.SortDirection;
}
