/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Resource {
    resource_id: string;
    resource_type: Scout.ResourceResourceType;
}
