// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * List of layout revisions response
 */
export interface RevisionListResponse {
    ok?: boolean;
    revisions?: Scout.BriefingLayoutRevision[];
}
