// This file was auto-generated by Fern from our API Definition.

/**
 * Search request model
 */
export interface SearchRequest {
    /** Search query text */
    query?: string;
    /** Type of search */
    search_type?: SearchRequest.SearchType;
    /** Additional filters to apply */
    filters?: Record<string, unknown>;
    /** Maximum results to return */
    limit?: number;
}

export namespace SearchRequest {
    /** Type of search */
    export const SearchType = {
        Keyword: "keyword",
        Vector: "vector",
        Hybrid: "hybrid",
    } as const;
    export type SearchType = (typeof SearchType)[keyof typeof SearchType];
}
