/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Merge: upsert documents keying off site url. Replace: merge and remove stale documents.
 */
export type SourceSyncCrawlSettingsInputMode = "merge" | "replace";
export const SourceSyncCrawlSettingsInputMode = {
    Merge: "merge",
    Replace: "replace",
} as const;
