// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface SourceSyncCrawlSettingsInput {
    source_archetype_id: "com.scoutos.crawl";
    /** The starting URL for the crawl process. */
    start_urls: string;
    crawler_settings?: Scout.MultiPageCrawlerSettingsInput;
    /** Merge: upsert documents keying off site url. Replace: merge and remove stale documents. */
    mode?: SourceSyncCrawlSettingsInput.Mode;
}

export namespace SourceSyncCrawlSettingsInput {
    /** Merge: upsert documents keying off site url. Replace: merge and remove stale documents. */
    export const Mode = {
        Merge: "merge",
        Replace: "replace",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
