/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SourceArchetype {
    /** The unique identifier for this source archetype */
    archetype_id: string;
    /** The human readable name for this source archetype */
    display_name: string;
    /** A description of this source archetype */
    description?: string;
    /** Wether or not this Source can be schedule to run at an interval */
    schedulable?: boolean;
    /** A URL to an image representing this source archetype */
    img_url?: string;
    /** The input schema for this source archetype */
    input_schema: Record<string, unknown>;
    /** Determines if the SourceSync is a IntegratedService */
    integrated_service_id?: string;
}
