// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface SrcAppHttpRoutesCollectionGetScheduledSyncsResponse {
    size: number;
    syncs: Scout.Sync[];
    updated_syncs: string[];
    disabled_syncs: string[];
}
