// This file was auto-generated by Fern from our API Definition.

/**
 * Delete response
 */
export interface SrcAppHttpRoutesBriefingBriefingRoutesDeleteResponse {
    ok?: boolean;
    message?: string;
}
