/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface SrcAppHttpRoutesInboxHandleMessageIncomingMessage {
    /** The content of the incoming message */
    content: Scout.SrcAppHttpRoutesInboxHandleMessageIncomingMessageContent;
    /** The type of content in the message */
    content_type: Scout.SrcAppHttpRoutesInboxHandleMessageIncomingMessageContentType;
}
