// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface SrcAppHttpRoutesWorldInteractInteractionRequest {
    messages: Scout.SrcAppHttpRoutesWorldInteractIncomingMessage[];
    /** Optional metadata (e.g., salesforce_session) */
    metadata?: Record<string, unknown>;
}
