/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The content of the incoming message
 */
export type SrcAppHttpRoutesInboxHandleMessageIncomingMessageContent = string | Record<string, unknown>;
