// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface SrcAppHttpRoutesBillingGetInvoicesData {
    invoices: Scout.FriendlyInvoice[];
}
