/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface SrcHandlersPromoteWorkflowRevisionResponse {
    data?: Scout.Workflow;
}
