/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface Subscription {
    plan: Scout.PlanTypes;
    interval: Scout.Interval;
}
