/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index.js";

export interface SyncConfigOutput {
    source_settings: SyncConfigOutput.SourceSettings;
    destination: Scout.CollectionDestination;
    mapping: Scout.Mapping;
    schedule?: Scout.Schedule;
}

export namespace SyncConfigOutput {
    export type SourceSettings =
        | Scout.SourceSyncGoogleDriveSettings
        | Scout.SourceSyncNotionSettingsOutput
        | Scout.SourceSyncCrawlSettingsOutput
        | Scout.SourceSyncPageCrawlSettingsOutput
        | Scout.SourceSyncSitemapSettingsOutput
        | Scout.SourceSyncWebsiteSettings;
}
