/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export type SyncConfigOutputSourceSettings =
    | Scout.SourceSyncNotionSettings
    | Scout.SourceSyncCrawlSettingsOutput
    | Scout.SourceSyncPageCrawlSettingsOutput
    | Scout.SourceSyncSitemapSettingsOutput
    | Scout.SourceSyncWebsiteSettings;
