// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface TableConfigOutput {
    table_display_name?: string;
    table_img_url?: string;
    table_description?: string;
    schema?: TableConfigOutput.Schema.Item[];
    icon_emoji?: string;
    icon_asset_url?: string;
    icon_fill?: string;
    plural_name?: string;
}

export namespace TableConfigOutput {
    export type Schema = Schema.Item[];

    export namespace Schema {
        export type Item =
            | Scout.CheckBoxColumn
            | Scout.DateTimeColumn
            | Scout.JsonColumn
            | Scout.MarkdownColumn
            | Scout.MultiSelectColumn
            | Scout.NumberColumn
            | Scout.PeopleColumn
            | Scout.RelationColumn
            | Scout.SelectColumn
            | Scout.TextLongColumn
            | Scout.TextShortColumn
            | Scout.UrlColumn;
    }
}
