/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface TableViewSettings {
    column_visibility?: Record<string, boolean>;
    column_order?: string[];
    column_widths?: Record<string, number>;
    type: "table";
    row_height?: Scout.TableViewSettingsRowHeight;
    show_row_numbers?: boolean;
    wrap_text?: boolean;
}
