// This file was auto-generated by Fern from our API Definition.

import * as Scout from "../index.js";

export interface TableViewSettingsInput {
    column_visibility?: Record<string, boolean>;
    column_order?: string[];
    column_widths?: Record<string, number>;
    type: "table";
    row_height?: TableViewSettingsInput.RowHeight;
    show_row_numbers?: boolean;
    wrap_text?: boolean;
    filters?: Scout.ViewFilter[];
}

export namespace TableViewSettingsInput {
    export const RowHeight = {
        Compact: "compact",
        Medium: "medium",
        Tall: "tall",
    } as const;
    export type RowHeight = (typeof RowHeight)[keyof typeof RowHeight];
}
