/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TextExtractor = "readability" | "trafilatura" | "custom";

export const TextExtractor = {
    Readability: "readability",
    Trafilatura: "trafilatura",
    Custom: "custom",
} as const;
