// This file was auto-generated by Fern from our API Definition.

export const TextExtractor = {
    Readability: "readability",
    Trafilatura: "trafilatura",
    Custom: "custom",
} as const;
export type TextExtractor = (typeof TextExtractor)[keyof typeof TextExtractor];
