/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface TrafilaturaInput {
    text_extractor_type: "trafilatura";
    /** Choose the Trafilatura extraction algorithm to use. */
    trafilatura_type: Scout.TrafilaturaInputTrafilaturaType;
}
