/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateCronAuthResponse {
    total_jobs_found: number;
    jobs_needing_update: number;
    total_jobs_updated: number;
    updated_jobs: Record<string, unknown>[];
    errors: Record<string, unknown>[];
}
