// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * Checklist of CRM updates with action buttons.
 */
export interface UpdateChecklistBlock {
    type: "update_checklist";
    id?: string;
    title?: string;
    items: Scout.UpdateChecklistItem[];
    apply_all_action?: Scout.BlockAction;
}
