// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

/**
 * Request to update existing feedback
 */
export interface UpdateFeedbackRequest {
    score?: number;
    selected_option?: string;
    comment?: string;
    correction?: unknown;
    metadata?: UpdateFeedbackRequest.Metadata;
    status?: UpdateFeedbackRequest.Status;
    priority?: UpdateFeedbackRequest.Priority;
    assigned_to?: string;
    internal_notes?: string;
}

export namespace UpdateFeedbackRequest {
    export type Metadata = Scout.GenericFeedbackMetadata | Scout.WorkflowRunFeedbackMetadata;
    export const Status = {
        New: "new",
        Open: "open",
        InProgress: "in_progress",
        Resolved: "resolved",
        Closed: "closed",
        WontFix: "wont_fix",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Priority = {
        Low: "low",
        Medium: "medium",
        High: "high",
        Critical: "critical",
    } as const;
    export type Priority = (typeof Priority)[keyof typeof Priority];
}
