/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UsageTypes =
    | "crawl"
    | "storage"
    | "web_search"
    | "input_tokens"
    | "output_tokens"
    | "text_embedding"
    | "workflow_invocations";
export const UsageTypes = {
    Crawl: "crawl",
    Storage: "storage",
    WebSearch: "web_search",
    InputTokens: "input_tokens",
    OutputTokens: "output_tokens",
    TextEmbedding: "text_embedding",
    WorkflowInvocations: "workflow_invocations",
} as const;
