// This file was auto-generated by Fern from our API Definition.

export interface UserIdentityDetails {
    user_id: string;
    org_id: string;
    scout_organization_id: string;
    email: Record<string, unknown>;
}
