/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserIdentity {
    userId: string;
    orgId: string;
    scoutOrganizationId: string;
    email: Record<string, unknown>;
}
