// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../index.js";

export interface ViewFilter {
    id?: string;
    column_id: string;
    operator?: Scout.FilterOperator;
    value?: unknown;
    enabled?: boolean;
    created_at?: string;
}
