// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata for workflow_run target type.
 */
export interface WorkflowRunFeedbackMetadata {
    target_type: "workflow_run";
    /** The workflow definition ID for navigation */
    workflow_id: string;
    /** The session ID */
    session_id: string;
    /** The workflow run ID (same as target_id) */
    run_id: string;
}
