/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface WorkflowRunStartedData {
    actor?: Scout.Actor;
    workflow_id: string;
    workflow_run_id?: string;
    inputs: Record<string, unknown>;
    session_id?: string;
    state?: Record<string, unknown>;
    workflow_config?: Record<string, unknown>;
    price: number;
}
