/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type WorkflowRunEvent = "app_run_started" | "app_run_completed" | "app_run_failed";

export const WorkflowRunEvent = {
    AppRunStarted: "app_run_started",
    AppRunCompleted: "app_run_completed",
    AppRunFailed: "app_run_failed",
} as const;
