/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../index";

export interface Workflow {
    workflowConfig: Scout.WorkflowConfigOutput;
    lastUpdatedAt: Date;
    createdAt: Date;
    createdBy: Scout.Identity;
    lastUpdatedBy: Scout.Identity;
    revisionId: string;
    workflowId: string;
    isDraft?: boolean;
}
