// This file was auto-generated by Fern from our API Definition.

import * as Scout from "../index.js";

/**
 * Hook model for workflow targets.
 */
export interface WorkflowHook {
    id: string;
    organization_id: string;
    name: string;
    description?: string;
    target_id: string;
    status?: string;
    response_mode?: string;
    allowed_methods?: string[];
    max_payload_size?: number;
    secret?: string;
    url?: string;
    created_at: string;
    updated_at: string;
    created_by?: Record<string, unknown>;
    target_type: "workflow";
    target_config: Scout.WorkflowTargetConfig;
}
