// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface CreateCollectionRequest {
    collection_display_name?: string;
    collection_img_url?: string;
    collection_description?: string;
    tags?: string[];
    table_order?: string[];
    /** Optional user-provided collection ID. Must be a lowercase slug (a-z, 0-9, hyphens, underscores) between 3 and 63 characters. If omitted, an ID is auto-generated. */
    collection_id?: string;
}
