/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../../../index";

/**
 * @example
 *     {}
 */
export interface UpdateViewRequest {
    name?: string;
    type?: Scout.UpdateViewRequestType;
    emoji?: string;
    settings?: Scout.UpdateViewRequestSettings;
    visibility?: Scout.ViewVisibility;
    shared_with?: string[];
    filters?: Scout.ViewFilter[];
    query?: Scout.ViewQueryInput;
}
