// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../../../../index.js";

/**
 * @example
 *     {
 *         view_state: {
 *             organization_id: "organization_id",
 *             collection_id: "collection_id"
 *         }
 *     }
 */
export interface UpdateViewStateRequest {
    view_state: Scout.CollectionViewStateInput;
}
