// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         question_ids: ["question_ids"],
 *         questionnaire_id: "questionnaire_id"
 *     }
 */
export interface BatchGenerateRequest {
    question_ids: string[];
    questionnaire_id: string;
}
