/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         agent: "agent",
 *         revision: "revision"
 *     }
 */
export interface BodyUpsertAgentAgentsPost {
    agent: string;
    agent_id?: string;
    activate?: boolean;
    revision: string;
}
