/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../index";

/**
 * @example
 *     {
 *         auth_type: "api_key"
 *     }
 */
export interface ConnectIntegrationRequest {
    auth_type: Scout.ConnectIntegrationRequestAuthType;
    api_key?: string;
    code?: string;
    state?: string;
    scope?: string;
    client_id?: string;
    client_secret?: string;
    environment?: string;
}
