// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_type: "api_key"
 *     }
 */
export interface ConnectIntegrationRequest {
    auth_type: ConnectIntegrationRequest.AuthType;
    api_key?: string;
    code?: string;
    state?: string;
    scope?: string;
    client_id?: string;
    client_secret?: string;
    environment?: string;
}

export namespace ConnectIntegrationRequest {
    export const AuthType = {
        ApiKey: "api_key",
        Oauth2: "oauth2",
        Oauth2Custom: "oauth2_custom",
    } as const;
    export type AuthType = (typeof AuthType)[keyof typeof AuthType];
}
