// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface EntityQueryRequest {
    /** 'agent' or 'object' */
    entity_type?: string;
    /** Filter activities that entities appear in */
    activity_filters?: Record<string, unknown>;
    /** Activities must have these tags */
    tags?: string[];
    /** Activities must have these outcomes */
    outcomes?: string[];
    /** Activities must have these actions */
    actions?: string[];
    /** Time range for activities */
    time?: Record<string, unknown>;
    /** Entity kinds to include (user, team, document, etc) */
    kinds?: string[];
    /** Entity roles to include */
    roles?: string[];
    /** Return only current state via quantum collapse */
    current_state?: boolean;
    /** Include activity statistics for each entity */
    include_stats?: boolean;
    /** Group entities by field (kind, role) */
    group_by?: string;
    limit?: number;
    /** Minimum activities for entity to be included */
    min_activities?: number;
}
