/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetUsageAccountsUsageGetRequest {
    start_date?: string;
    end_date?: string;
}
