/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         channel_id: "channel_id",
 *         thread_id: "thread_id",
 *         integration_id: "integration_id"
 *     }
 */
export interface HandleGetThreadIntegrationsSlackThreadGetRequest {
    channel_id: string;
    thread_id: string;
    integration_id?: string;
}
