// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         limit: 1,
 *         entity_type: "entity_type",
 *         current_state: true
 *     }
 */
export interface ListEntitiesPulseEntitiesGetRequest {
    limit?: number;
    /** Filter by entity type */
    entity_type?: string;
    /** Return only current state via quantum collapse */
    current_state?: boolean;
}
