/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../index.js";

/**
 * @example
 *     {
 *         messages: [{
 *                 content: "content",
 *                 content_type: "text/plain"
 *             }],
 *         participants: [{
 *                 id: "id"
 *             }]
 *     }
 */
export interface SrcAppHttpRoutesInboxHandleMessageInteractionRequest {
    messages: Scout.SrcAppHttpRoutesInboxHandleMessageIncomingMessage[];
    participants: SrcAppHttpRoutesInboxHandleMessageInteractionRequest.Participants.Item[];
    history?: Scout.SrcAppHttpRoutesInboxHandleMessageIncomingMessage[];
    files?: Scout.FilesAttribute[];
    mentions?: Scout.Mention[];
    ephemeral_agent_revision?: Scout.AgentRevision;
}

export namespace SrcAppHttpRoutesInboxHandleMessageInteractionRequest {
    export type Participants = Participants.Item[];

    export namespace Participants {
        export type Item = Scout.ScoutUser | Scout.AiAgent;
    }
}
