/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../index";

/**
 * @example
 *     {
 *         messages: [{
 *                 content: "content",
 *                 content_type: "text/plain"
 *             }],
 *         participants: [{
 *                 id: "id"
 *             }]
 *     }
 */
export interface SrcAppHttpRoutesInboxHandleMessageInteractionRequest {
    messages: Scout.SrcAppHttpRoutesInboxHandleMessageIncomingMessage[];
    participants: Scout.SrcAppHttpRoutesInboxHandleMessageInteractionRequestParticipantsItem[];
    history?: Scout.SrcAppHttpRoutesInboxHandleMessageIncomingMessage[];
    files?: Scout.FilesAttribute[];
    ephemeral_agent_revision?: Scout.AgentRevision;
}
