/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         agent_ids: ["agent_ids"],
 *         resource_ids: ["resource_ids"]
 *     }
 */
export interface SrcAppHttpRoutesDriveRevokeAccessPayload {
    agent_ids: string[];
    resource_ids: string[];
}
