/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../index";

/**
 * @example
 *     {
 *         source_sync_settings: {
 *             source_archetype_id: "com.google.drive"
 *         },
 *         url: "url"
 *     }
 */
export interface SrcAppHttpRoutesDriveCreateDriveCrawlPayload {
    source_sync_settings: Scout.SrcAppHttpRoutesDriveCreateDriveCrawlPayloadSourceSyncSettings;
    schedule?: Scout.Schedule;
    url: string;
}
