// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         type: "type",
 *         prefix: "prefix"
 *     }
 */
export interface StoreGetTagsPulseStoreTagsGetRequest {
    type?: string;
    prefix?: string;
}
