// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateTagsRequest {
    /** Entity ID */
    id: string;
    /** Tags to add */
    add_tags?: string[];
    /** Tags to remove */
    remove_tags?: string[];
}
