/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         file_ids: ["file_ids"]
 *     }
 */
export interface UpdateQuestionnaireFilesRequest {
    file_ids: string[];
}
