/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scout from "../../../../api/index";
import * as core from "../../../../core";
import { Channel } from "../../../types/Channel";

export const Response: core.serialization.Schema<serializers.integrations.listChannels.Response.Raw, Scout.Channel[]> =
    core.serialization.list(Channel);

export declare namespace Response {
    export type Raw = Channel.Raw[];
}
