/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const ActivitySchema: core.serialization.ObjectSchema<serializers.ActivitySchema.Raw, Scout.ActivitySchema> =
    core.serialization.object({
        title: core.serialization.string(),
        icon: core.serialization.string(),
        applies_to: core.serialization.list(core.serialization.string()),
        primary_object: core.serialization.string().optional(),
        properties: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        relationships: core.serialization
            .record(
                core.serialization.string(),
                core.serialization.record(core.serialization.string(), core.serialization.unknown()),
            )
            .optional(),
        quick_action: core.serialization.boolean().optional(),
        context_hints: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace ActivitySchema {
    export interface Raw {
        title: string;
        icon: string;
        applies_to: string[];
        primary_object?: string | null;
        properties: Record<string, unknown>;
        relationships?: Record<string, Record<string, unknown>> | null;
        quick_action?: boolean | null;
        context_hints?: Record<string, unknown> | null;
    }
}
