/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const ActionType: core.serialization.Schema<serializers.ActionType.Raw, Scout.ActionType> =
    core.serialization.enum_(["workflow.execute", "source.sync"]);

export declare namespace ActionType {
    export type Raw = "workflow.execute" | "source.sync";
}
