/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const AgentRevisionResponseStyle: core.serialization.Schema<
    serializers.AgentRevisionResponseStyle.Raw,
    Scout.AgentRevisionResponseStyle
> = core.serialization.enum_(["precise", "balanced", "creative", "experimental", "json"]);

export declare namespace AgentRevisionResponseStyle {
    export type Raw = "precise" | "balanced" | "creative" | "experimental" | "json";
}
