/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const AgentRevisionModel: core.serialization.Schema<
    serializers.AgentRevisionModel.Raw,
    Scout.AgentRevisionModel
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("_dynamic"),
    core.serialization.string(),
]);

export declare namespace AgentRevisionModel {
    export type Raw = "_dynamic" | string;
}
