/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const AppRunCompletedEnvironment: core.serialization.Schema<
    serializers.AppRunCompletedEnvironment.Raw,
    Scout.AppRunCompletedEnvironment
> = core.serialization.enum_(["development", "preview", "production", "test"]);

export declare namespace AppRunCompletedEnvironment {
    type Raw = "development" | "preview" | "production" | "test";
}
