/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { EventName } from "./EventName";
import { EventVersion } from "./EventVersion";
import { AppRunStartedEnvironment } from "./AppRunStartedEnvironment";
import { AppRunStartedData } from "./AppRunStartedData";

export const AppRunStarted: core.serialization.ObjectSchema<serializers.AppRunStarted.Raw, Scout.AppRunStarted> =
    core.serialization.object({
        organizationId: core.serialization.property("organization_id", core.serialization.string()),
        id: core.serialization.string().optional(),
        correlationId: core.serialization.property("correlation_id", core.serialization.string().optional()),
        name: EventName.optional(),
        version: EventVersion.optional(),
        environment: AppRunStartedEnvironment,
        timestamp: core.serialization.string().optional(),
        data: AppRunStartedData,
    });

export declare namespace AppRunStarted {
    interface Raw {
        organization_id: string;
        id?: string | null;
        correlation_id?: string | null;
        name?: EventName.Raw | null;
        version?: EventVersion.Raw | null;
        environment: AppRunStartedEnvironment.Raw;
        timestamp?: string | null;
        data: AppRunStartedData.Raw;
    }
}
