/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const AppsServiceHandlersDeleteAppRevisionResponse: core.serialization.ObjectSchema<
    serializers.AppsServiceHandlersDeleteAppRevisionResponse.Raw,
    Scout.AppsServiceHandlersDeleteAppRevisionResponse
> = core.serialization.object({
    detail: core.serialization.string(),
});

export declare namespace AppsServiceHandlersDeleteAppRevisionResponse {
    interface Raw {
        detail: string;
    }
}
