/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const AutomationTargetConfig: core.serialization.ObjectSchema<
    serializers.AutomationTargetConfig.Raw,
    Scout.AutomationTargetConfig
> = core.serialization.object({
    automation_mode: core.serialization.string().optional(),
});

export declare namespace AutomationTargetConfig {
    export interface Raw {
        automation_mode?: string | null;
    }
}
