/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const BlockStateUpdatedEnvironment: core.serialization.Schema<
    serializers.BlockStateUpdatedEnvironment.Raw,
    Scout.BlockStateUpdatedEnvironment
> = core.serialization.enum_(["development", "preview", "production", "test"]);

export declare namespace BlockStateUpdatedEnvironment {
    export type Raw = "development" | "preview" | "production" | "test";
}
