/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { EventVersion } from "./EventVersion";
import { BlockRunFailedEnvironment } from "./BlockRunFailedEnvironment";
import { BlockRunFailedData } from "./BlockRunFailedData";

export const BlockRunFailed: core.serialization.ObjectSchema<serializers.BlockRunFailed.Raw, Scout.BlockRunFailed> =
    core.serialization.object({
        organizationId: core.serialization.property("organization_id", core.serialization.string()),
        id: core.serialization.string().optional(),
        correlationId: core.serialization.property("correlation_id", core.serialization.string().optional()),
        version: EventVersion.optional(),
        environment: BlockRunFailedEnvironment,
        timestamp: core.serialization.string().optional(),
        data: BlockRunFailedData,
    });

export declare namespace BlockRunFailed {
    interface Raw {
        organization_id: string;
        id?: string | null;
        correlation_id?: string | null;
        version?: EventVersion.Raw | null;
        environment: BlockRunFailedEnvironment.Raw;
        timestamp?: string | null;
        data: BlockRunFailedData.Raw;
    }
}
