/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Document } from "./Document";

export const CollectionServiceHandlersGetDocumentsResponse: core.serialization.ObjectSchema<
    serializers.CollectionServiceHandlersGetDocumentsResponse.Raw,
    Scout.CollectionServiceHandlersGetDocumentsResponse
> = core.serialization.object({
    data: core.serialization.list(Document).optional(),
});

export declare namespace CollectionServiceHandlersGetDocumentsResponse {
    interface Raw {
        data?: Document.Raw[] | null;
    }
}
