/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Collection } from "./Collection";

export const CollectionServiceHandlersUpdateCollectionResponse: core.serialization.ObjectSchema<
    serializers.CollectionServiceHandlersUpdateCollectionResponse.Raw,
    Scout.CollectionServiceHandlersUpdateCollectionResponse
> = core.serialization.object({
    data: Collection.optional(),
});

export declare namespace CollectionServiceHandlersUpdateCollectionResponse {
    export interface Raw {
        data?: Collection.Raw | null;
    }
}
