/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const ColumnTypeItemNumberMinValue: core.serialization.Schema<
    serializers.ColumnTypeItemNumberMinValue.Raw,
    Scout.ColumnTypeItemNumberMinValue
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.number()]);

export declare namespace ColumnTypeItemNumberMinValue {
    type Raw = number | number;
}
