/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const CopilotConfigMode: core.serialization.Schema<serializers.CopilotConfigMode.Raw, Scout.CopilotConfigMode> =
    core.serialization.enum_(["light", "dark"]);

export declare namespace CopilotConfigMode {
    export type Raw = "light" | "dark";
}
