/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { CronTriggerConfigAction } from "./CronTriggerConfigAction";
import { TriggerStatus } from "./TriggerStatus";

export const CronTriggerConfig: core.serialization.ObjectSchema<
    serializers.CronTriggerConfig.Raw,
    Scout.CronTriggerConfig
> = core.serialization.object({
    trigger_display_name: core.serialization.string().optional(),
    trigger_type: core.serialization.stringLiteral("cron"),
    action: CronTriggerConfigAction,
    status: TriggerStatus.optional(),
    cron_expression: core.serialization.string(),
    timezone: core.serialization.string().optional(),
    trigger_inputs: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace CronTriggerConfig {
    export interface Raw {
        trigger_display_name?: string | null;
        trigger_type: "cron";
        action: CronTriggerConfigAction.Raw;
        status?: TriggerStatus.Raw | null;
        cron_expression: string;
        timezone?: string | null;
        trigger_inputs?: Record<string, unknown> | null;
    }
}
