/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const Custom: core.serialization.ObjectSchema<serializers.Custom.Raw, Scout.Custom> = core.serialization.object({
    text_extractor_type: core.serialization.stringLiteral("custom"),
    selectors: core.serialization.string().optional(),
    exclude_selectors: core.serialization.string().optional(),
    exclude_common_elements: core.serialization.boolean().optional(),
});

export declare namespace Custom {
    export interface Raw {
        text_extractor_type: "custom";
        selectors?: string | null;
        exclude_selectors?: string | null;
        exclude_common_elements?: boolean | null;
    }
}
