/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { DateTimeColumnAutomationConfig } from "./DateTimeColumnAutomationConfig";

export const DateTimeColumn: core.serialization.ObjectSchema<serializers.DateTimeColumn.Raw, Scout.DateTimeColumn> =
    core.serialization.object({
        column_id: core.serialization.string().optional(),
        column_display_name: core.serialization.string().optional(),
        column_type: core.serialization.stringLiteral("datetime"),
        data_type: core.serialization.stringLiteral("datetime").optional(),
        hidden: core.serialization.boolean().optional(),
        automation_config: DateTimeColumnAutomationConfig.optional(),
        default: core.serialization.date().optional(),
    });

export declare namespace DateTimeColumn {
    export interface Raw {
        column_id?: string | null;
        column_display_name?: string | null;
        column_type: "datetime";
        data_type?: "datetime" | null;
        hidden?: boolean | null;
        automation_config?: DateTimeColumnAutomationConfig.Raw | null;
        default?: string | null;
    }
}
