/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const DeleteViewResponse: core.serialization.ObjectSchema<
    serializers.DeleteViewResponse.Raw,
    Scout.DeleteViewResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    error: core.serialization.string().optional(),
});

export declare namespace DeleteViewResponse {
    export interface Raw {
        success: boolean;
        error?: string | null;
    }
}
