/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { DocumentDataOutput } from "./DocumentDataOutput";
import { Identity } from "./Identity";

export const Document: core.serialization.ObjectSchema<serializers.Document.Raw, Scout.Document> =
    core.serialization.object({
        document_id: core.serialization.string().optional(),
        data: DocumentDataOutput,
        created_at: core.serialization.date().optional(),
        last_updated_at: core.serialization.date().optional(),
        created_by: Identity,
        last_updated_by: Identity,
    });

export declare namespace Document {
    interface Raw {
        document_id?: string | null;
        data: DocumentDataOutput.Raw;
        created_at?: string | null;
        last_updated_at?: string | null;
        created_by: Identity.Raw;
        last_updated_by: Identity.Raw;
    }
}
