/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { DocumentDataValue } from "./DocumentDataValue";
import { DocumentCreatedBy } from "./DocumentCreatedBy";
import { DocumentLastUpdatedBy } from "./DocumentLastUpdatedBy";

export const Document: core.serialization.ObjectSchema<serializers.Document.Raw, Scout.Document> =
    core.serialization.object({
        document_id: core.serialization.string().optional(),
        data: core.serialization.record(core.serialization.string(), DocumentDataValue.optional()).optional(),
        document_data_id: core.serialization.string().optional(),
        created_at: core.serialization.date().optional(),
        last_updated_at: core.serialization.date().optional(),
        created_by: DocumentCreatedBy,
        last_updated_by: DocumentLastUpdatedBy,
        revision_id: core.serialization.string().optional(),
        job_id: core.serialization.string().optional(),
        sync_id: core.serialization.string().optional(),
        studio_row: core.serialization.boolean().optional(),
        cells: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace Document {
    export interface Raw {
        document_id?: string | null;
        data?: Record<string, DocumentDataValue.Raw | null | undefined> | null;
        document_data_id?: string | null;
        created_at?: string | null;
        last_updated_at?: string | null;
        created_by: DocumentCreatedBy.Raw;
        last_updated_by: DocumentLastUpdatedBy.Raw;
        revision_id?: string | null;
        job_id?: string | null;
        sync_id?: string | null;
        studio_row?: boolean | null;
        cells?: Record<string, unknown> | null;
    }
}
