/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const EnvironmentDeploymentConfigRevisionLookup: core.serialization.Schema<
    serializers.EnvironmentDeploymentConfigRevisionLookup.Raw,
    Scout.EnvironmentDeploymentConfigRevisionLookup
> = core.serialization.enum_(["latest", "revision_id"]);

export declare namespace EnvironmentDeploymentConfigRevisionLookup {
    type Raw = "latest" | "revision_id";
}
