/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Table } from "./Table";

export const EvalServiceHandlersGetTablesResponse: core.serialization.ObjectSchema<
    serializers.EvalServiceHandlersGetTablesResponse.Raw,
    Scout.EvalServiceHandlersGetTablesResponse
> = core.serialization.object({
    data: core.serialization.list(Table).optional(),
});

export declare namespace EvalServiceHandlersGetTablesResponse {
    interface Raw {
        data?: Table.Raw[] | null;
    }
}
