/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const FavoriteRef: core.serialization.ObjectSchema<serializers.FavoriteRef.Raw, Scout.FavoriteRef> =
    core.serialization.object({
        id: core.serialization.string(),
        type: core.serialization.string(),
    });

export declare namespace FavoriteRef {
    export interface Raw {
        id: string;
        type: string;
    }
}
