/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const FollowupEmailRequest: core.serialization.ObjectSchema<
    serializers.FollowupEmailRequest.Raw,
    Scout.FollowupEmailRequest
> = core.serialization.object({
    days: core.serialization.list(core.serialization.number()).optional(),
});

export declare namespace FollowupEmailRequest {
    export interface Raw {
        days?: number[] | null;
    }
}
