/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { ApiKeyAuthType } from "./ApiKeyAuthType";
import { McpAuthType } from "./McpAuthType";
import { OAuthAuthType } from "./OAuthAuthType";

export const IntegrationAuthType: core.serialization.Schema<
    serializers.IntegrationAuthType.Raw,
    Scout.IntegrationAuthType
> = core.serialization.undiscriminatedUnion([ApiKeyAuthType, McpAuthType, OAuthAuthType]);

export declare namespace IntegrationAuthType {
    export type Raw = ApiKeyAuthType.Raw | McpAuthType.Raw | OAuthAuthType.Raw;
}
