/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { IntegrationWithConnectionsId } from "./IntegrationWithConnectionsId";
import { IntegrationAuthType } from "./IntegrationAuthType";
import { IntegrationConnection } from "./IntegrationConnection";

export const IntegrationWithConnections: core.serialization.ObjectSchema<
    serializers.IntegrationWithConnections.Raw,
    Scout.IntegrationWithConnections
> = core.serialization.object({
    name: core.serialization.string(),
    id: IntegrationWithConnectionsId,
    auth_client: core.serialization.string(),
    description: core.serialization.string(),
    auth_types: core.serialization.list(IntegrationAuthType),
    icon_url: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    tags: core.serialization.list(core.serialization.string()).optional(),
    enabled: core.serialization.boolean().optional(),
    permissions: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
    auth_configs: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    connected: core.serialization.boolean(),
    connections: core.serialization.list(IntegrationConnection),
    existing_auth_client_scope: core.serialization.list(core.serialization.string()),
    supports_multiple_connections: core.serialization.boolean(),
});

export declare namespace IntegrationWithConnections {
    export interface Raw {
        name: string;
        id: IntegrationWithConnectionsId.Raw;
        auth_client: string;
        description: string;
        auth_types: IntegrationAuthType.Raw[];
        icon_url?: string | null;
        metadata?: Record<string, unknown> | null;
        tags?: string[] | null;
        enabled?: boolean | null;
        permissions?: Record<string, unknown>[] | null;
        auth_configs?: Record<string, unknown> | null;
        connected: boolean;
        connections: IntegrationConnection.Raw[];
        existing_auth_client_scope: string[];
        supports_multiple_connections: boolean;
    }
}
