/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { TypescriptAutomationConfig } from "./TypescriptAutomationConfig";

export const JsonColumn: core.serialization.ObjectSchema<serializers.JsonColumn.Raw, Scout.JsonColumn> =
    core.serialization.object({
        column_id: core.serialization.string().optional(),
        column_display_name: core.serialization.string().optional(),
        column_type: core.serialization.stringLiteral("json"),
        data_type: core.serialization.stringLiteral("string").optional(),
        hidden: core.serialization.boolean().optional(),
        automation_config: TypescriptAutomationConfig.optional(),
        default: core.serialization.string().optional(),
    });

export declare namespace JsonColumn {
    export interface Raw {
        column_id?: string | null;
        column_display_name?: string | null;
        column_type: "json";
        data_type?: "string" | null;
        hidden?: boolean | null;
        automation_config?: TypescriptAutomationConfig.Raw | null;
        default?: string | null;
    }
}
