/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { ActorIdentity } from "./ActorIdentity";
import { UserOrganizationConfig } from "./UserOrganizationConfig";
import { FavoriteItem } from "./FavoriteItem";

export const Me: core.serialization.ObjectSchema<serializers.Me.Raw, Scout.Me> = core.serialization.object({
    id: core.serialization.string().optional(),
    doc_type: core.serialization.stringLiteral("user").optional(),
    created_by: ActorIdentity,
    updated_by: ActorIdentity,
    created_at: core.serialization.date().optional(),
    updated_at: core.serialization.date().optional(),
    is_seed: core.serialization.boolean().optional(),
    first_name: core.serialization.string(),
    last_name: core.serialization.string(),
    email_address: core.serialization.string(),
    inbox_welcome_message_sent: core.serialization.boolean().optional(),
    consent: core.serialization.record(core.serialization.string(), core.serialization.boolean().optional()).optional(),
    use_cases: core.serialization.list(core.serialization.string()).optional(),
    lead_id: core.serialization.string().optional(),
    organizations: core.serialization.record(core.serialization.string(), UserOrganizationConfig).optional(),
    favorites: core.serialization.list(FavoriteItem).optional(),
});

export declare namespace Me {
    export interface Raw {
        id?: string | null;
        doc_type?: "user" | null;
        created_by: ActorIdentity.Raw;
        updated_by: ActorIdentity.Raw;
        created_at?: string | null;
        updated_at?: string | null;
        is_seed?: boolean | null;
        first_name: string;
        last_name: string;
        email_address: string;
        inbox_welcome_message_sent?: boolean | null;
        consent?: Record<string, boolean | null | undefined> | null;
        use_cases?: string[] | null;
        lead_id?: string | null;
        organizations?: Record<string, UserOrganizationConfig.Raw> | null;
        favorites?: FavoriteItem.Raw[] | null;
    }
}
