/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { MentionParticipant } from "./MentionParticipant";

export const Mention: core.serialization.ObjectSchema<serializers.Mention.Raw, Scout.Mention> =
    core.serialization.object({
        participant: MentionParticipant,
    });

export declare namespace Mention {
    export interface Raw {
        participant: MentionParticipant.Raw;
    }
}
