/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const ParticipantType: core.serialization.Schema<serializers.ParticipantType.Raw, Scout.ParticipantType> =
    core.serialization.enum_(["scout_user", "ai_agent"]);

export declare namespace ParticipantType {
    export type Raw = "scout_user" | "ai_agent";
}
