/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { PlaceholderInputType } from "./PlaceholderInputType";
import { NodeUi } from "./NodeUi";
import { Dependency } from "./Dependency";

export const PlaceholderInput: core.serialization.ObjectSchema<
    serializers.PlaceholderInput.Raw,
    Scout.PlaceholderInput
> = core.serialization.object({
    block_id: core.serialization.string(),
    type: PlaceholderInputType,
    ui: NodeUi.optional(),
    dependencies: core.serialization.list(Dependency).optional(),
});

export declare namespace PlaceholderInput {
    export interface Raw {
        block_id: string;
        type: PlaceholderInputType.Raw;
        ui?: NodeUi.Raw | null;
        dependencies?: Dependency.Raw[] | null;
    }
}
