/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const PlaceholderInputType: core.serialization.Schema<
    serializers.PlaceholderInputType.Raw,
    Scout.PlaceholderInputType
> = core.serialization.enum_(["triggerPlaceholder", "blockPlaceholder"]);

export declare namespace PlaceholderInputType {
    export type Raw = "triggerPlaceholder" | "blockPlaceholder";
}
