/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const PlanTypes: core.serialization.Schema<serializers.PlanTypes.Raw, Scout.PlanTypes> =
    core.serialization.enum_([
        "plan_1",
        "plan_2",
        "plan_7357",
        "plan_3",
        "plan_4",
        "plan_5",
        "plan_6",
        "plan_7",
        "plan_8",
        "plan_9",
        "plan_10",
        "plan_11",
        "plan_12",
        "plan_13",
        "plan_14",
        "plan_15",
    ]);

export declare namespace PlanTypes {
    export type Raw =
        | "plan_1"
        | "plan_2"
        | "plan_7357"
        | "plan_3"
        | "plan_4"
        | "plan_5"
        | "plan_6"
        | "plan_7"
        | "plan_8"
        | "plan_9"
        | "plan_10"
        | "plan_11"
        | "plan_12"
        | "plan_13"
        | "plan_14"
        | "plan_15";
}
