/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const PulseFeedResponse: core.serialization.ObjectSchema<
    serializers.PulseFeedResponse.Raw,
    Scout.PulseFeedResponse
> = core.serialization.object({
    ok: core.serialization.boolean(),
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace PulseFeedResponse {
    export interface Raw {
        ok: boolean;
        data: Record<string, unknown>;
    }
}
