/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const QueryBuilderRequestSortDirection: core.serialization.Schema<
    serializers.QueryBuilderRequestSortDirection.Raw,
    Scout.QueryBuilderRequestSortDirection
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace QueryBuilderRequestSortDirection {
    export type Raw = "asc" | "desc";
}
