/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { ResourceResourceType } from "./ResourceResourceType";

export const Resource: core.serialization.ObjectSchema<serializers.Resource.Raw, Scout.Resource> =
    core.serialization.object({
        resource_id: core.serialization.string(),
        resource_type: ResourceResourceType,
    });

export declare namespace Resource {
    export interface Raw {
        resource_id: string;
        resource_type: ResourceResourceType.Raw;
    }
}
