/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Rule } from "./Rule";

export const RulesOutput: core.serialization.ObjectSchema<serializers.RulesOutput.Raw, Scout.RulesOutput> =
    core.serialization.object({
        rules: core.serialization.list(Rule).optional(),
    });

export declare namespace RulesOutput {
    export interface Raw {
        rules?: Rule.Raw[] | null;
    }
}
