/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SourceArchetype: core.serialization.ObjectSchema<serializers.SourceArchetype.Raw, Scout.SourceArchetype> =
    core.serialization.object({
        archetype_id: core.serialization.string(),
        display_name: core.serialization.string(),
        description: core.serialization.string().optional(),
        schedulable: core.serialization.boolean().optional(),
        img_url: core.serialization.string().optional(),
        input_schema: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        integrated_service_id: core.serialization.string().optional(),
    });

export declare namespace SourceArchetype {
    export interface Raw {
        archetype_id: string;
        display_name: string;
        description?: string | null;
        schedulable?: boolean | null;
        img_url?: string | null;
        input_schema: Record<string, unknown>;
        integrated_service_id?: string | null;
    }
}
