/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SourceSyncPageCrawlSettingsOutputMode: core.serialization.Schema<
    serializers.SourceSyncPageCrawlSettingsOutputMode.Raw,
    Scout.SourceSyncPageCrawlSettingsOutputMode
> = core.serialization.enum_(["merge", "replace"]);

export declare namespace SourceSyncPageCrawlSettingsOutputMode {
    export type Raw = "merge" | "replace";
}
