/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SourceSyncNotionSettings: core.serialization.ObjectSchema<
    serializers.SourceSyncNotionSettings.Raw,
    Scout.SourceSyncNotionSettings
> = core.serialization.object({
    source_archetype_id: core.serialization.stringLiteral("com.notion.notion"),
    api_key: core.serialization.string().optional(),
});

export declare namespace SourceSyncNotionSettings {
    interface Raw {
        source_archetype_id: "com.notion.notion";
        api_key?: string | null;
    }
}
