/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { NotionFilterOptions } from "./NotionFilterOptions";

export const SourceSyncNotionSettingsOutput: core.serialization.ObjectSchema<
    serializers.SourceSyncNotionSettingsOutput.Raw,
    Scout.SourceSyncNotionSettingsOutput
> = core.serialization.object({
    source_archetype_id: core.serialization.stringLiteral("com.notion.notion"),
    api_key: core.serialization.string().optional(),
    filter_options: core.serialization.list(NotionFilterOptions).optional(),
});

export declare namespace SourceSyncNotionSettingsOutput {
    export interface Raw {
        source_archetype_id: "com.notion.notion";
        api_key?: string | null;
        filter_options?: NotionFilterOptions.Raw[] | null;
    }
}
