/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SrcAppHttpRoutesCollectionDeleteCollectionResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesCollectionDeleteCollectionResponse.Raw,
    Scout.SrcAppHttpRoutesCollectionDeleteCollectionResponse
> = core.serialization.object({
    detail: core.serialization.string(),
});

export declare namespace SrcAppHttpRoutesCollectionDeleteCollectionResponse {
    export interface Raw {
        detail: string;
    }
}
