/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Notification } from "./Notification";

export const SrcAppHttpRoutesBillingGetNotificationsResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesBillingGetNotificationsResponse.Raw,
    Scout.SrcAppHttpRoutesBillingGetNotificationsResponse
> = core.serialization.object({
    data: core.serialization.list(Notification),
});

export declare namespace SrcAppHttpRoutesBillingGetNotificationsResponse {
    export interface Raw {
        data: Notification.Raw[];
    }
}
