/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { SrcAppHttpRoutesBillingGetInvoicesData } from "./SrcAppHttpRoutesBillingGetInvoicesData";

export const SrcAppHttpRoutesBillingGetInvoicesResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesBillingGetInvoicesResponse.Raw,
    Scout.SrcAppHttpRoutesBillingGetInvoicesResponse
> = core.serialization.object({
    data: SrcAppHttpRoutesBillingGetInvoicesData,
});

export declare namespace SrcAppHttpRoutesBillingGetInvoicesResponse {
    export interface Raw {
        data: SrcAppHttpRoutesBillingGetInvoicesData.Raw;
    }
}
