/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { SrcAppHttpRoutesBillingRenewPlansData } from "./SrcAppHttpRoutesBillingRenewPlansData";

export const SrcAppHttpRoutesBillingRenewPlansResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesBillingRenewPlansResponse.Raw,
    Scout.SrcAppHttpRoutesBillingRenewPlansResponse
> = core.serialization.object({
    data: SrcAppHttpRoutesBillingRenewPlansData,
});

export declare namespace SrcAppHttpRoutesBillingRenewPlansResponse {
    export interface Raw {
        data: SrcAppHttpRoutesBillingRenewPlansData.Raw;
    }
}
