/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SrcAppHttpRoutesCollectionDeleteSyncResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesCollectionDeleteSyncResponse.Raw,
    Scout.SrcAppHttpRoutesCollectionDeleteSyncResponse
> = core.serialization.object({
    detail: core.serialization.string(),
    status_code: core.serialization.number(),
});

export declare namespace SrcAppHttpRoutesCollectionDeleteSyncResponse {
    export interface Raw {
        detail: string;
        status_code: number;
    }
}
