/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SrcAppHttpRoutesBillingCreatePortalSessionData: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesBillingCreatePortalSessionData.Raw,
    Scout.SrcAppHttpRoutesBillingCreatePortalSessionData
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace SrcAppHttpRoutesBillingCreatePortalSessionData {
    export interface Raw {
        url: string;
    }
}
