/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Sync } from "./Sync";

export const SrcAppHttpRoutesCollectionGetSyncResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesCollectionGetSyncResponse.Raw,
    Scout.SrcAppHttpRoutesCollectionGetSyncResponse
> = core.serialization.object({
    data: Sync,
});

export declare namespace SrcAppHttpRoutesCollectionGetSyncResponse {
    export interface Raw {
        data: Sync.Raw;
    }
}
