/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Document } from "./Document";

export const SrcAppHttpRoutesCollectionGetDocumentResponse: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesCollectionGetDocumentResponse.Raw,
    Scout.SrcAppHttpRoutesCollectionGetDocumentResponse
> = core.serialization.object({
    data: Document.optional(),
});

export declare namespace SrcAppHttpRoutesCollectionGetDocumentResponse {
    export interface Raw {
        data?: Document.Raw | null;
    }
}
