/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { SourceArchetype } from "./SourceArchetype";

export const SrcAppHttpRoutesCollectionListSourceArchetypesResponseModel: core.serialization.ObjectSchema<
    serializers.SrcAppHttpRoutesCollectionListSourceArchetypesResponseModel.Raw,
    Scout.SrcAppHttpRoutesCollectionListSourceArchetypesResponseModel
> = core.serialization.object({
    sources: core.serialization.list(SourceArchetype),
});

export declare namespace SrcAppHttpRoutesCollectionListSourceArchetypesResponseModel {
    export interface Raw {
        sources: SourceArchetype.Raw[];
    }
}
