/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Workflow } from "./Workflow";

export const SrcHandlersListWorkflowsResponse: core.serialization.ObjectSchema<
    serializers.SrcHandlersListWorkflowsResponse.Raw,
    Scout.SrcHandlersListWorkflowsResponse
> = core.serialization.object({
    data: core.serialization.list(Workflow),
    next_cursor: core.serialization.date().optional(),
    has_more: core.serialization.boolean(),
});

export declare namespace SrcHandlersListWorkflowsResponse {
    export interface Raw {
        data: Workflow.Raw[];
        next_cursor?: string | null;
        has_more: boolean;
    }
}
