/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Workflow } from "./Workflow";

export const SrcHandlersCreateWorkflowRevisionResponse: core.serialization.ObjectSchema<
    serializers.SrcHandlersCreateWorkflowRevisionResponse.Raw,
    Scout.SrcHandlersCreateWorkflowRevisionResponse
> = core.serialization.object({
    data: Workflow.optional(),
});

export declare namespace SrcHandlersCreateWorkflowRevisionResponse {
    interface Raw {
        data?: Workflow.Raw | null;
    }
}
