/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const SrcHandlersUpdateWorkflowEnvironmentResponse: core.serialization.ObjectSchema<
    serializers.SrcHandlersUpdateWorkflowEnvironmentResponse.Raw,
    Scout.SrcHandlersUpdateWorkflowEnvironmentResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
});

export declare namespace SrcHandlersUpdateWorkflowEnvironmentResponse {
    export interface Raw {
        success: boolean;
    }
}
