/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { Copilot } from "./Copilot";

export const SrcHandlersListCopilotsResponse: core.serialization.ObjectSchema<
    serializers.SrcHandlersListCopilotsResponse.Raw,
    Scout.SrcHandlersListCopilotsResponse
> = core.serialization.object({
    data: core.serialization.list(Copilot),
    next_cursor: core.serialization.date().optional(),
    has_more: core.serialization.boolean(),
});

export declare namespace SrcHandlersListCopilotsResponse {
    interface Raw {
        data: Copilot.Raw[];
        next_cursor?: string | null;
        has_more: boolean;
    }
}
