/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { EntityResponse } from "./EntityResponse";

export const StoreResponse: core.serialization.ObjectSchema<serializers.StoreResponse.Raw, Scout.StoreResponse> =
    core.serialization.object({
        ok: core.serialization.boolean().optional(),
        entity: EntityResponse.optional(),
        entities: core.serialization.list(EntityResponse).optional(),
        message: core.serialization.string().optional(),
    });

export declare namespace StoreResponse {
    export interface Raw {
        ok?: boolean | null;
        entity?: EntityResponse.Raw | null;
        entities?: EntityResponse.Raw[] | null;
        message?: string | null;
    }
}
