/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const StripeProvider: core.serialization.ObjectSchema<serializers.StripeProvider.Raw, Scout.StripeProvider> =
    core.serialization.object({
        provider: core.serialization.stringLiteral("stripe"),
        customer_id: core.serialization.string(),
    });

export declare namespace StripeProvider {
    export interface Raw {
        provider: "stripe";
        customer_id: string;
    }
}
