/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { SourceSyncGoogleDriveSettings } from "./SourceSyncGoogleDriveSettings";
import { SourceSyncNotionSettingsInput } from "./SourceSyncNotionSettingsInput";
import { SourceSyncCrawlSettingsInput } from "./SourceSyncCrawlSettingsInput";
import { SourceSyncPageCrawlSettingsInput } from "./SourceSyncPageCrawlSettingsInput";
import { SourceSyncSitemapSettingsInput } from "./SourceSyncSitemapSettingsInput";
import { SourceSyncWebsiteSettings } from "./SourceSyncWebsiteSettings";

export const SyncConfigInputSourceSettings: core.serialization.Schema<
    serializers.SyncConfigInputSourceSettings.Raw,
    Scout.SyncConfigInputSourceSettings
> = core.serialization.undiscriminatedUnion([
    SourceSyncGoogleDriveSettings,
    SourceSyncNotionSettingsInput,
    SourceSyncCrawlSettingsInput,
    SourceSyncPageCrawlSettingsInput,
    SourceSyncSitemapSettingsInput,
    SourceSyncWebsiteSettings,
]);

export declare namespace SyncConfigInputSourceSettings {
    export type Raw =
        | SourceSyncGoogleDriveSettings.Raw
        | SourceSyncNotionSettingsInput.Raw
        | SourceSyncCrawlSettingsInput.Raw
        | SourceSyncPageCrawlSettingsInput.Raw
        | SourceSyncSitemapSettingsInput.Raw
        | SourceSyncWebsiteSettings.Raw;
}
