/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { SyncConfigOutput } from "./SyncConfigOutput";
import { Identity } from "./Identity";

export const Sync: core.serialization.ObjectSchema<serializers.Sync.Raw, Scout.Sync> = core.serialization.object({
    sync_config: SyncConfigOutput,
    sync_id: core.serialization.string(),
    trigger_id: core.serialization.string().optional(),
    last_updated_at: core.serialization.date(),
    created_at: core.serialization.date(),
    created_by: Identity,
    last_updated_by: Identity,
});

export declare namespace Sync {
    export interface Raw {
        sync_config: SyncConfigOutput.Raw;
        sync_id: string;
        trigger_id?: string | null;
        last_updated_at: string;
        created_at: string;
        created_by: Identity.Raw;
        last_updated_by: Identity.Raw;
    }
}
