/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const TableViewSettingsOutputRowHeight: core.serialization.Schema<
    serializers.TableViewSettingsOutputRowHeight.Raw,
    Scout.TableViewSettingsOutputRowHeight
> = core.serialization.enum_(["compact", "medium", "tall"]);

export declare namespace TableViewSettingsOutputRowHeight {
    export type Raw = "compact" | "medium" | "tall";
}
