/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { ToolsData } from "./ToolsData";

export const ToolsResponse: core.serialization.ObjectSchema<serializers.ToolsResponse.Raw, Scout.ToolsResponse> =
    core.serialization.object({
        data: ToolsData,
    });

export declare namespace ToolsResponse {
    export interface Raw {
        data: ToolsData.Raw;
    }
}
