/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const ToolConfigResourceType: core.serialization.Schema<
    serializers.ToolConfigResourceType.Raw,
    Scout.ToolConfigResourceType
> = core.serialization.enum_(["tables", "workflow", "crawl", "file", "integration"]);

export declare namespace ToolConfigResourceType {
    export type Raw = "tables" | "workflow" | "crawl" | "file" | "integration";
}
