/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const ToolDetails: core.serialization.ObjectSchema<serializers.ToolDetails.Raw, Scout.ToolDetails> =
    core.serialization.object({
        tool_name: core.serialization.string(),
        tool_cname: core.serialization.string(),
        group: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        icon_url: core.serialization.string().optional(),
        input_schema: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        labels: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace ToolDetails {
    export interface Raw {
        tool_name: string;
        tool_cname: string;
        group?: string | null;
        description?: string | null;
        icon_url?: string | null;
        input_schema?: Record<string, unknown> | null;
        labels?: string[] | null;
    }
}
