/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { BareOutput } from "./BareOutput";
import { Baseline } from "./Baseline";
import { DefaultOutput } from "./DefaultOutput";
import { Html2Text } from "./Html2Text";

export const TrafilaturaOutputTrafilaturaType: core.serialization.Schema<
    serializers.TrafilaturaOutputTrafilaturaType.Raw,
    Scout.TrafilaturaOutputTrafilaturaType
> = core.serialization.undiscriminatedUnion([BareOutput, Baseline, DefaultOutput, Html2Text]);

export declare namespace TrafilaturaOutputTrafilaturaType {
    type Raw = BareOutput.Raw | Baseline.Raw | DefaultOutput.Raw | Html2Text.Raw;
}
