/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const Units: core.serialization.Schema<serializers.Units.Raw, Scout.Units> =
    core.serialization.stringLiteral("USD");

export declare namespace Units {
    export type Raw = "USD";
}
