/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const UsageTypes: core.serialization.Schema<serializers.UsageTypes.Raw, Scout.UsageTypes> =
    core.serialization.enum_([
        "crawl",
        "storage",
        "web_search",
        "input_tokens",
        "output_tokens",
        "text_embedding",
        "workflow_invocations",
    ]);

export declare namespace UsageTypes {
    export type Raw =
        | "crawl"
        | "storage"
        | "web_search"
        | "input_tokens"
        | "output_tokens"
        | "text_embedding"
        | "workflow_invocations";
}
