/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { ViewListResponseDataItem } from "./ViewListResponseDataItem";

export const ViewListResponse: core.serialization.ObjectSchema<
    serializers.ViewListResponse.Raw,
    Scout.ViewListResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    data: core.serialization.list(ViewListResponseDataItem).optional(),
    error: core.serialization.string().optional(),
});

export declare namespace ViewListResponse {
    export interface Raw {
        success: boolean;
        data?: ViewListResponseDataItem.Raw[] | null;
        error?: string | null;
    }
}
