/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { EventVersion } from "./EventVersion";
import { WorkflowRunStartedEnvironment } from "./WorkflowRunStartedEnvironment";
import { WorkflowRunStartedData } from "./WorkflowRunStartedData";

export const WorkflowRunStarted: core.serialization.ObjectSchema<
    serializers.WorkflowRunStarted.Raw,
    Scout.WorkflowRunStarted
> = core.serialization.object({
    organization_id: core.serialization.string(),
    id: core.serialization.string().optional(),
    correlation_id: core.serialization.string().optional(),
    name: core.serialization.stringLiteral("workflow_run_started").optional(),
    version: EventVersion.optional(),
    environment: WorkflowRunStartedEnvironment,
    timestamp: core.serialization.string().optional(),
    data: WorkflowRunStartedData,
});

export declare namespace WorkflowRunStarted {
    interface Raw {
        organization_id: string;
        id?: string | null;
        correlation_id?: string | null;
        name?: "workflow_run_started" | null;
        version?: EventVersion.Raw | null;
        environment: WorkflowRunStartedEnvironment.Raw;
        timestamp?: string | null;
        data: WorkflowRunStartedData.Raw;
    }
}
