/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { WorkflowRunEvent } from "./WorkflowRunEvent";

export const WorkflowRunResponseStreaming: core.serialization.ObjectSchema<
    serializers.WorkflowRunResponseStreaming.Raw,
    Scout.WorkflowRunResponseStreaming
> = core.serialization.object({
    event: WorkflowRunEvent,
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace WorkflowRunResponseStreaming {
    interface Raw {
        event: WorkflowRunEvent.Raw;
        data: Record<string, unknown>;
    }
}
