/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const WorkflowRunCompletedData: core.serialization.ObjectSchema<
    serializers.WorkflowRunCompletedData.Raw,
    Scout.WorkflowRunCompletedData
> = core.serialization.object({
    workflowId: core.serialization.property("workflow_id", core.serialization.string()),
    workflowRunId: core.serialization.property("workflow_run_id", core.serialization.string()),
    output: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    sessionId: core.serialization.property("session_id", core.serialization.string()),
    workflowConfig: core.serialization.property(
        "workflow_config",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
});

export declare namespace WorkflowRunCompletedData {
    interface Raw {
        workflow_id: string;
        workflow_run_id: string;
        output: Record<string, unknown>;
        session_id: string;
        workflow_config?: Record<string, unknown> | null;
    }
}
