/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";

export const WorkflowAutomationConfig: core.serialization.ObjectSchema<
    serializers.WorkflowAutomationConfig.Raw,
    Scout.WorkflowAutomationConfig
> = core.serialization
    .object({
        mode: core.serialization.stringLiteral("workflow"),
        button_text: core.serialization.string().optional(),
        executing_text: core.serialization.string().optional(),
    })
    .passthrough();

export declare namespace WorkflowAutomationConfig {
    export interface Raw {
        mode: "workflow";
        button_text?: string | null;
        executing_text?: string | null;
        [key: string]: any;
    }
}
