/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { FieldMapping } from "./FieldMapping";

export const WorkflowTargetConfig: core.serialization.ObjectSchema<
    serializers.WorkflowTargetConfig.Raw,
    Scout.WorkflowTargetConfig
> = core.serialization.object({
    field_mappings: core.serialization.list(FieldMapping).optional(),
    default_field_id: core.serialization.string().optional(),
    run_mode: core.serialization.string().optional(),
    timeout_seconds: core.serialization.number().optional(),
    verify_token: core.serialization.string().optional(),
});

export declare namespace WorkflowTargetConfig {
    export interface Raw {
        field_mappings?: FieldMapping.Raw[] | null;
        default_field_id?: string | null;
        run_mode?: string | null;
        timeout_seconds?: number | null;
        verify_token?: string | null;
    }
}
