/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scout from "../../api/index";
import * as core from "../../core";
import { WorkflowRunResponseBatchData } from "./WorkflowRunResponseBatchData";

export const WorkflowRunResponseBatch: core.serialization.ObjectSchema<
    serializers.WorkflowRunResponseBatch.Raw,
    Scout.WorkflowRunResponseBatch
> = core.serialization.object({
    data: WorkflowRunResponseBatchData,
});

export declare namespace WorkflowRunResponseBatch {
    interface Raw {
        data: WorkflowRunResponseBatchData.Raw;
    }
}
