// This file was auto-generated by Fern from our API Definition.

import * as Scout from "../../src/api/index";
import { ScoutClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Usage", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ScoutClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { data: { usage: [{ total_cost: 1.1 }], total_cost: 1.1 } };
        server.mockEndpoint().get("/v2/usage").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.usage.get({
            start_date: "start_date",
            end_date: "end_date",
        });
        expect(response).toEqual({
            data: {
                usage: [
                    {
                        total_cost: 1.1,
                    },
                ],
                total_cost: 1.1,
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ScoutClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server.mockEndpoint().get("/v2/usage").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.usage.get();
        }).rejects.toThrow(Scout.UnprocessableEntityError);
    });
});
