// This file was auto-generated by Fern from our API Definition.

import * as Scout from "../../src/api/index";
import { ScoutClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WorkflowLogs", () => {
    test("get_details (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ScoutClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            workflow_display_name: "workflow_display_name",
            workflow_run_id: "workflow_run_id",
            workflow_id: "workflow_id",
            status: "status",
            session_id: "session_id",
            environment: "environment",
            revision_id: "revision_id",
            cost: 1.1,
            blocks: {
                key: {
                    block_archetype_id: "block_archetype_id",
                    block_type: "block_type",
                    block_id: "block_id",
                    block_display_name: "block_display_name",
                    block_inputs: { key: "value" },
                    block_output: { key: "value" },
                    config: { key: "value" },
                    metadata: { key: "value" },
                    elapsed_time_ms: 1,
                    cost: 1.1,
                    message: "message",
                    workflow_state: { key: "value" },
                    status: "status",
                    timestamp_start: "2024-01-15T09:30:00Z",
                    timestamp_end: "2024-01-15T09:30:00Z",
                },
            },
            output: { key: "value" },
            elapsed_time_ms: 1,
            timestamp_start: "2024-01-15T09:30:00Z",
            timestamp_end: "2024-01-15T09:30:00Z",
            message: "message",
            gcs_log_path: "gcs_log_path",
        };
        server
            .mockEndpoint()
            .get("/v2/run_logs/details")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.workflowLogs.getDetails({
            workflow_id: "workflow_id",
            session_id: "session_id",
            workflow_run_id: "workflow_run_id",
        });
        expect(response).toEqual({
            workflow_display_name: "workflow_display_name",
            workflow_run_id: "workflow_run_id",
            workflow_id: "workflow_id",
            status: "status",
            session_id: "session_id",
            environment: "environment",
            revision_id: "revision_id",
            cost: 1.1,
            blocks: {
                key: {
                    block_archetype_id: "block_archetype_id",
                    block_type: "block_type",
                    block_id: "block_id",
                    block_display_name: "block_display_name",
                    block_inputs: {
                        key: "value",
                    },
                    block_output: {
                        key: "value",
                    },
                    config: {
                        key: "value",
                    },
                    metadata: {
                        key: "value",
                    },
                    elapsed_time_ms: 1,
                    cost: 1.1,
                    message: "message",
                    workflow_state: {
                        key: "value",
                    },
                    status: "status",
                    timestamp_start: "2024-01-15T09:30:00Z",
                    timestamp_end: "2024-01-15T09:30:00Z",
                },
            },
            output: {
                key: "value",
            },
            elapsed_time_ms: 1,
            timestamp_start: "2024-01-15T09:30:00Z",
            timestamp_end: "2024-01-15T09:30:00Z",
            message: "message",
            gcs_log_path: "gcs_log_path",
        });
    });

    test("get_details (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ScoutClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/v2/run_logs/details")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.workflowLogs.getDetails({
                workflow_id: "workflow_id",
            });
        }).rejects.toThrow(Scout.UnprocessableEntityError);
    });
});
