// This file was auto-generated by Fern from our API Definition.

export const ScoutEnvironment = {
    Prod: "https://api.scoutos.com",
} as const;

export type ScoutEnvironment = typeof ScoutEnvironment.Prod;
