// This file was auto-generated by Fern from our API Definition.

import type * as Scout from "../../../../index.js";

/**
 * @example
 *     {
 *         job_id: "job_id",
 *         sync_id: "sync_id",
 *         await_completion: true,
 *         mode: "mode",
 *         body: {
 *             "key": true
 *         }
 *     }
 */
export interface DocumentsCreateRequest {
    /** The job id responsible for the document creation/update */
    job_id?: string;
    /** The sync id the job belongs to thats responsible for the document creation/update */
    sync_id?: string;
    /** Whether to wait for document creation/update to complete */
    await_completion?: boolean;
    /** The mode to use for the document creation/update */
    mode?: string;
    body: Scout.DocumentsCreateRequestBody;
}
