/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scout from "../../../../index";

/**
 * @example
 *     {}
 */
export interface TableData {
    table_display_name?: string;
    table_img_url?: string;
    table_description?: string;
    schema?: Scout.TableDataSchemaItem[];
    index_id?: string;
}
